-- USER SQL
CREATE USER bit IDENTIFIED BY 1004 
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER bit QUOTA UNLIMITED ON USERS;

-- ROLES
GRANT "CONNECT" TO bit ;
GRANT "RESOURCE" TO bit ;

-- SYSTEM PRIVILEGES